name: smartqueue
description: A queue management app for Registrar's Office
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Backend & Database
  supabase_flutter: ^2.3.4
  
  # State Management
  provider: ^6.1.1
  
  # UI & Animations
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.2
  
  # Enhanced Features
  shared_preferences: ^2.2.2  # Offline storage
  connectivity_plus: ^5.0.2   # Network connectivity
  #flutter_local_notifications: ^15.1.3  # Push notifications
  permission_handler: ^11.2.0  # Permissions
  package_info_plus: ^4.2.0    # App info
  url_launcher: ^6.2.2         # External links
  
  # Development & Debugging
  logger: ^2.0.2               # Better logging
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
    
  