// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkHAan9ssa1mc3cZw8wQrqfy5DrqLuvNI',
    appId: '1:439664392698:web:8efe996d5058b2e1618c43',
    messagingSenderId: '439664392698',
    projectId: 'smartqueue-1f6a2',
    authDomain: 'smartqueue-1f6a2.firebaseapp.com',
    storageBucket: 'smartqueue-1f6a2.firebasestorage.app',
    measurementId: 'G-LMHEWRDEBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8VyMnq6e7jD_ZbVMQrwm8XhYy4ocgLXc',
    appId: '1:439664392698:android:759ca7fd05b33ccd618c43',
    messagingSenderId: '439664392698',
    projectId: 'smartqueue-1f6a2',
    storageBucket: 'smartqueue-1f6a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBda1eLXXkRls9jhLoss1js5jeiX_kdN6E',
    appId: '1:439664392698:ios:bef0fd52507f32e1618c43',
    messagingSenderId: '439664392698',
    projectId: 'smartqueue-1f6a2',
    storageBucket: 'smartqueue-1f6a2.firebasestorage.app',
    iosBundleId: 'com.smartqueue.smartQueue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBda1eLXXkRls9jhLoss1js5jeiX_kdN6E',
    appId: '1:439664392698:ios:bef0fd52507f32e1618c43',
    messagingSenderId: '439664392698',
    projectId: 'smartqueue-1f6a2',
    storageBucket: 'smartqueue-1f6a2.firebasestorage.app',
    iosBundleId: 'com.smartqueue.smartQueue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkHAan9ssa1mc3cZw8wQrqfy5DrqLuvNI',
    appId: '1:439664392698:web:e91ca6d8e8565075618c43',
    messagingSenderId: '439664392698',
    projectId: 'smartqueue-1f6a2',
    authDomain: 'smartqueue-1f6a2.firebaseapp.com',
    storageBucket: 'smartqueue-1f6a2.firebasestorage.app',
    measurementId: 'G-4WC7Y00EKE',
  );
}
